#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm test
npx lint-staged

if [ "$(uname)" == "Darwin" ]; then
    npm run test
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    npm run test   
elif [ "$(expr substr $(uname -s) 1 5)" == "MINGW" ]; then
    npm run testWin
fi
